# Generated by Django 6.0.1 on 2026-02-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_socialproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='socialproject',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
