# Generated by Django 6.0.1 on 2026-03-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_researchproject_url_socialproject_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='button_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socialproject',
            name='button_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
