# Generated by Django 6.0.1 on 2026-03-01 07:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='출판 목록'),
        ),
    ]
