# Generated by Django 6.0.1 on 2026-02-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='degree',
            field=models.CharField(choices=[('undergrad', '학부'), ('master', '석사'), ('phd', '박사')], max_length=10),
        ),
    ]
