# Generated by Django 6.0.1 on 2026-02-18 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django_ckeditor_5.fields import CKEditor5Field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', CKEditor5Field(...)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='notice/photos/')),
                ('file', models.FileField(blank=True, null=True, upload_to='notice/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
