# Generated by Django 6.0.1 on 2026-02-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-id']},
        ),
    ]
