# Generated by Django 6.0.1 on 2026-02-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_notice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-is_important', '-id']},
        ),
        migrations.AddField(
            model_name='notice',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
