# Generated by Django 6.0.1 on 2026-02-20 12:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_notice_options_notice_is_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='내용'),
        ),
    ]
